### ISSUE TITLE
Channel numbers on list -a

### ISSUE THREAD

**Issue by sfjuocekr** [eried/FlipperZeroMayhem#11]
The original ESP Marauder shows the channel numbers when you do a list -a, this helps tremendously when you need to know what channel to sniff on for PMKID's.

**Comment by eried** [comment]
also in the flipper version? this is a fork of that project so it should behave the same 🙂

**Comment by sfjuocekr** [comment]
Maybe the way it shows was changed, but when I use marauder on the WiFi devboard it does show me channels when I do a list -a.

There have been quite a few changes to marauder over the past weeks/months. For example the EAPOL messages used to show no MAC address on the wifi devboard like your ESP32CAM version does, but on the wifi devboard they do show MAC addresses now.

**Comment by eried** [comment]
mmm, but when you say original marauder what do you mean? I do not really understand what changes you refer to. This is based on marauder esp32 so it should be the same behaviour unless something changed last weeks

**Comment by sfjuocekr** [comment]
When I say original Marauder I meant pulled from https://github.com/justcallmekoko/ESP32Marauder/

I have since build my own from that repo with some changes and got it working like a bare bones marauder at the moment. It also seems to support BT!

Also your "base" marauder version is 10.3, which was indeed missing channels and BSSID output.

**Comment by eried** [comment]
Yes, it will be updated soon
