### ISSUE TITLE
Apps compiled for Xtreme

### ISSUE THREAD

**Issue by srolfe** [eried/FlipperZeroMayhem#2]
Since they don't live in the repo I figured I'd just upload them as an issue if you wanted to include those in your getting started page.

Thanks for the board, it's pretty great so far!

[esp32cam_compiled_xtreme.zip](https://github.com/eried/flipperzero-mayhem/files/10885153/esp32cam_compiled_xtreme.zip)

**Comment by eried** [comment]
hi, thanks! sorry for the big delay. I never saw any notifications :/ but as you see now they are compiled to anything :)
