### ISSUE TITLE
Serial Connection To ESP in wrong mode

### ISSUE THREAD

**Issue by MadPanda404** [eried/FlipperZeroMayhem#31]
Hey

When i connect my Flipper to usb and use any serial tool (screen, putty, and so on), input works as intended (i can edit my input and then hit enter so its get sent). But when i then switch the flipper in USB-to-UART, to use the marauder cli ion the mayhem v2 fin, i need to type really fast because input does not get send line by line, but key by key. is there a way to fix that?

**Comment by eried** [comment]
is this in putty? or where

**Comment by MadPanda404** [comment]
In putty, macos terminal, screen, i term... basically any terminal toolAm 20.01.2024 01:16 schrieb Erwin Ried ***@***.***>:
is this in putty? or where

**Comment by eried** [comment]
I guess you set your bauds manually, but it should be 230400 for the ESP32 in this case -> check [this](https://github.com/eried/flipperzero-mayhem/wiki/Troubleshooting#the-apps-are-not-talking-with-the-esp32)
