### ISSUE TITLE
DIY version - Second module slot wiring unclear

### ISSUE THREAD

**Issue by jdude104** [eried/FlipperZeroMayhem#33]
Hello, I was working on trying to put together the DIY version of the mayhem board following the wiki page, but I'm having some uncertainty when it comes to the second module slot. It says to "change the external module side as implemented in this version" but the link provided doesn't seem to provide much clarity. How is the second slot wired so that the SPI for the lower does not collide with the upper? If you were to follow the pinouts linked, there would be collision due to shared CS pin when you have both a cc1101 and nrf24.

**Comment by eried** [comment]
Hi, sorry for the delay, on the original version each side is a different module, that is why seems unclear :)

You need to physically flip the board to use the other module
