### ISSUE TITLE
API Mismatch

### ISSUE THREAD

**Issue by ldxjy** [eried/FlipperZeroMayhem#34]
hi there, I downloaded mayhem camera.fap 0.13.6,I used it with unleashed firmware 071e, when I run mayhem camera.fap 0.13.6 it says "API mismatch",I pressed continue, then flipper said" Load failed,update firmware to use with this application(missing imports)"
I dont know what's the problem,any ideas?
what should I do to run mayhem apps with unleashed firmware 071e?
thanks!

**Comment by eried** [comment]
Hi! the faps are exclusive for each firmware version, so it is difficult to provide files for all versions, you could: 1) install xtreme 2) compile the faps yourself https://github.com/eried/flipperzero-mayhem/wiki/Compilation-of-the-faps :)

**Comment by ldxjy** [comment]
> Hi! the faps are exclusive for each firmware version, so it is difficult to provide files for all versions, you could: 1) install xtreme 2) compile the faps yourself https://github.com/eried/flipperzero-mayhem/wiki/Compilation-of-the-faps :)

thanks for reply, I will look into it, it not easy for a normal guy,haha
but unleashed maybe the most popular OFW, hope someone will compile unleashed version.
thank you

**Comment by eried** [comment]
It was included before, but I am not sure why it disappeared. I started using xtreme because of that and it is actually better :)

Give it a go, it should be easy after doing it once
