### ISSUE TITLE
can't get evil portal mayhem app to load 

### ISSUE THREAD

**Issue by dav3shanahan** [eried/FlipperZeroMayhem#39]
I can't get Evil Portal to load on either Momentum or Xtreme firmwares. When using the Marauder MAYHEM app, I am able to scan for access points, but when I try to start Evil Portal, within marauder, I either get an error screen, a blank screen, or the flipper reboots due to 'out of memory' message.

All of the other MAYHEM apps work just fine with the board;  QRCODE, Morse flasher, nanny cam, motion detector, and camera, just not evil portal. I also tested Evil Portal using the official wifi dev board and it worked, but the mayhem evil portal app is just not working. Any suggestions?

**Comment by eried** [comment]
You need to update the firmware, evil portal was added in one of the latest :)
