### ISSUE TITLE
Firmware update? To latest marauder? 

### ISSUE THREAD

**Issue by j0p3s** [eried/FlipperZeroMayhem#42]
Hi. Any idea when this will happen? Thanks in advance

**Comment by eried** [comment]
oh, yes I think I should update :) maybe next weekend

**Comment by j0p3s** [comment]
Thanks buddy. Have a great day

A quinta, 23/05/2024, 14:18, Erwin Ried ***@***.***> escreveu:

**Comment by eried** [comment]
If you have a way to compile it, the new one is up on the next branch. I will test it for few days before releasing it officially to the updater, to check everything works ok. It was many tiny changes this time

**Comment by j0p3s** [comment]
what are the steps to compile it? Got a tutorial?

**Comment by eried** [comment]
https://github.com/eried/flipperzero-mayhem/wiki/Compilation-of-the-firmware

But might be not 100% working since last version, I am still testing

**Comment by j0p3s** [comment]
when compiling i get this error:

In file included from
C:\flipperzero-mayhem-next\esp32cam_marauder\EvilPortal.h:6,
                 from
C:\flipperzero-mayhem-next\esp32cam_marauder\esp32cam_marauder.ino:14:
C:\flipperzero-mayhem-next\esp32cam_marauder\ESPAsyncWebServer.h:31:10:
fatal error: StringArray.h: No such file or directory
   31 | #include "StringArray.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: StringArray.h: No such file or directory



Erwin Ried ***@***.***> escreveu (terça, 28/05/2024 à(s)
08:11):

**Comment by j0p3s** [comment]
managed to fix that error but now i'm getting:

C:\flipperzero-mayhem-next\esp32cam_marauder\WiFiScan.cpp: In member
function 'void WiFiScan::executeSwiftpairSpam(EBLEPayloadType)':
C:\flipperzero-mayhem-next\esp32cam_marauder\WiFiScan.cpp:1911:5: error:
'esp_base_mac_addr_set' was not declared in this scope; did you mean
'esp_base_mac_addr'?
 1911 |     esp_base_mac_addr_set(macAddr);
      |     ^~~~~~~~~~~~~~~~~~~~~
      |     esp_base_mac_addr
Multiple libraries were found for "quirc.h"
  Used: C:\Users\Joao\Documents\Arduino\libraries\quirc_lib
  Not used: C:\Users\Joao\Documents\Arduino\libraries\ESP32QRCodeReader_Page
exit status 1

Compilation error: 'esp_base_mac_addr_set' was not declared in this scope;
did you mean 'esp_base_mac_addr'?

any ideas?


João Santos ***@***.***> escreveu (quinta,
30/05/2024 à(s) 02:14):

**Comment by eried** [comment]
Not sure, if you check https://github.com/justcallmekoko/ESP32Marauder/issues/418 seems to be also from marauder. I still havent finished working on the update. I need to update the wiki too

**Comment by j0p3s** [comment]
Did add that line under line 22 and the error persists

A quinta, 30/05/2024, 09:09, Erwin Ried ***@***.***> escreveu:

**Comment by eried** [comment]
OK, I need to compile myself first and ran tests, but I havent had time. If you solve it first just post here :)

**Comment by j0p3s** [comment]
Have been trying to fix this issue but no luck whatsoever. I'm not a
programmer so i can't fix it myself but i'll keep looking

Erwin Ried ***@***.***> escreveu (quinta, 30/05/2024 à(s)
09:59):

**Comment by eried** [comment]
If I use this: https://github.com/eried/flipperzero-mayhem/wiki/Compilation-of-the-firmware it compiles OK 

The instructions changed a little but you can try again now. I havent tested on the board, but at least compiles

**Comment by Inspirati** [comment]
simply add a forward declaration immediately before the function that calls it:

esp_err_t esp_base_mac_addr_set(uint8_t *Mac);
