### ISSUE TITLE
IRAM0 segment data does not fit.

### ISSUE THREAD

**Issue by runcom** [eried/FlipperZeroMayhem#43]
Seems like I've been able to compile everything but I get this at the end. I've been able to narrow the issue down to having PSRAM enabled in the board settings. If I disable it, it compiles, otherwise, it gives me this (notice I have no board attached yet, I'm just hitting "verify" in the arduino ide)

<img width="521" alt="Screenshot 2024-05-24 at 10 02 26" src="https://github.com/eried/flipperzero-mayhem/assets/849915/a5487b3d-e872-4927-970f-06150980b65f">

```
/Users/user1/Library/Arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /private/var/folders/2q/b_hxf6nn50ddy8s9s8prfvfh0000gn/T/arduino/sketches/EF35CDE55DCEC7F8DF8D89DE5D8D5621/esp32cam_marauder.ino.elf section `.iram0.text' will not fit in region `iram0_0_seg'
/Users/user1/Library/Arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: IRAM0 segment data does not fit.
/Users/user1/Library/Arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: region `iram0_0_seg' overflowed by 1344 bytes
collect2: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1
```

**Comment by eried** [comment]
oh! could you try with a different Partition Scheme? without OTA for example, it is only 1.3 kb overflow 😂

**Comment by runcom** [comment]
> oh! could you try with a different Partition Scheme? without OTA for example, it is only 1.3 kb overflow 😂

same, it doesn't matter which partition scheme I use, if psram is enabled, I get this error :/
do you know why this is happening at all tho? 🤔

**Comment by eried** [comment]
Not sure, because without psram I dont think the camera works. Is this the same code from this repo?

**Comment by runcom** [comment]
> Not sure, because without psram I dont think the camera works. Is this the same code from this repo?

yup, unchanged code from this repo - I'm on osx if that changes anything, using v2.0.10 as ESP32 library in arduino ide 🤷‍♂️

**Comment by runcom** [comment]
I think I've just bumped LinkedList from v1.3.1 to v1.3.3 and now it works.......no clue what happened

**Comment by eried** [comment]
oh, also I think esp32cam project now it is integrated to esp32, so I am not sure if now I should compile with the `AI Thinker ESP32-CAM` board instead. 

Eitherway, I need to update to latest marauder soon, so the code will change a bit.

**Comment by runcom** [comment]
> Eitherway, I need to update to latest marauder soon, so the code will change a bit.

neat, I've actually already updated marauder in my fork and it seems to be working pretty well too :)

**Comment by runcom** [comment]
also compiling for the ai thinker esp32-cam just works too :)

**Comment by eried** [comment]
oh could you PR the update?

**Comment by runcom** [comment]
> oh could you PR the update?

there you go https://github.com/eried/flipperzero-mayhem/pull/45
