### ISSUE TITLE
step/stl file for the board for case creation

### ISSUE THREAD

**Issue by ghost** [eried/FlipperZeroMayhem#5]
Hi. Amazing job with the mayhem.

Can you share the stp/stl file for the mayhem board? I would love to take it with me everywhere and I'm afraid to damaged it if I carry it in my pocket or bag.

**Comment by eried** [comment]
Hi, they are here -> https://github.com/eried/flipperzero-mayhem/tree/master/parts/practical

But the design is not 100% finished yet
