### ISSUE TITLE
Nanny cam on Xtreme

### ISSUE THREAD

**Issue by jetlagv1** [eried/FlipperZeroMayhem#6]
I finally received the Mayhem board after troubles with the Dutch mail. Ive flashed Xtreme to the flipper and went though the functionality of the Mayhem board. All is working fine but I cannot get the Nanny Cam to work. It shows the ssid and password and it will connect. A port scan shows port 80 open and i feel the ca heating up but when i enter the ip in the browser I get error messages. "Site cannot be reached, took too long to respond" and "Site did not send any data"

**Comment by eried** [comment]
Hi, strange. This is with the latest firmware on the esp too right? It would be helpful if you could test in unleashed (I dont think it is much relevant but just to confirm)

**Comment by jetlagv1** [comment]
Its with the firmware that you put on the esp before shipping. But it gets even stranger. I tried again later and it suddenly worked after hitting refresh many times but now its not working anymore :-/

**Comment by eried** [comment]
It might be something else then, can you try with another phone? It is difficult to diagnose something like this. I would recommend to update the firmware either way in case the included one was a previous version.

**Comment by jetlagv1** [comment]
I've flashed the latest firmware through your webinstaller and installed unleashed but the nannycam keeps giving problems. I've tried dozens of times and it worked only a few times. Its not really that important but its very strange that it will only function every once in a while.

One other thing is that the app installer pages give an error message (see screenshot)
![Nanycam](https://github.com/eried/flipperzero-mayhem/assets/5540477/302325fd-4504-4146-8289-4bb6e5718860)

**Comment by eried** [comment]
What happens if you connect from a PC? the same? I will test. The nanny cam app is using ESP32 simple streaming so if you say it works sometimes maybe there is another error, could you go to where you bought the board and click in the support there? (it will include your order number), maybe your esp32 has something wrong

**Comment by eried** [comment]
> One other thing is that the app installer pages give an error message (see screenshot)

Thanks, now it is fixed. It seems there is new rules for flipper apps

**Comment by jetlagv1** [comment]
> What happens if you connect from a PC? the same? I will test. The nanny cam app is using ESP32 simple streaming so if you say it works sometimes maybe there is another error, could you go to where you bought the board and click in the support there? (it will include your order number), maybe your esp32 has something wrong

I've bought the mayhem from you 😂.
I'm the guy with the shipping trouble from the Netherlands.
I have tried with a PC as well. And the same thing happens. I reload a zillion times and then suddenly it works

**Comment by eried** [comment]
> I'm the guy with the shipping trouble from the Netherlands.

order num? it has been more than a dozen to netherlands. I can check the test your board went thru.

> I reload a zillion times and then suddenly it works

When it does not work, does the page does not load or another type of error?

**Comment by eried** [comment]
But in any case I see that the code of nannycam is a bit unstable, sometimes I get no response from that ip (but no error, just like "stuck trying to load")

I will try to run more tests and try to find how to make it more reliable for a next firmware update.

**Comment by eried** [comment]
Hi, I will close this for now. Nannycam is unstable in general, depending on the phone and PC. If you manage to find a way to always produce a fail and some more insights just post them here
