### ISSUE TITLE
Date of update on firmware?

### ISSUE THREAD

**Issue by j0p3s** [eried/FlipperZeroMayhem#7]
Hi Eried. Can you please add a date or a version number to the page of the firmware update?
Its easier to keep track when firmware is updated to your mayhem hat. 

Thanks

**Comment by eried** [comment]
hi, yes good idea. I still need to structure things, so it is mainly WIP for now. Thats why I havent polished things

**Comment by j0p3s** [comment]
Thanks a lot buddy. It's just easier to know when a new firmware is
available

**Comment by eried** [comment]
yes, next update will at least have datetime somewhere 👍
