### ISSUE TITLE
Switching mode not working

### ISSUE THREAD

**Issue by tim-db** [eried/FlipperZeroMayhem#8]
I installed the ESP firmware with the webinstaller and I have the xtreme flipper zero firmware.
The mayhem marauder app fully works but the other apps don't.
For example the camera app stays on "Waiting ESP32-CAM"

Any advice on how to solve or debug?

**Comment by eried** [comment]
Hi, you need to disconnect the usb cable for the switching to work :)

I havent found an easy workaround
